# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sixth.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.setWindowModality(QtCore.Qt.NonModal)
        main.resize(1231, 318)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main.sizePolicy().hasHeightForWidth())
        main.setSizePolicy(sizePolicy)
        main.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        main.setAcceptDrops(False)
        main.setAutoFillBackground(False)
        main.setModal(False)
        self.videoWidget = QVideoWidget(main)
        self.videoWidget.setGeometry(QtCore.QRect(20, 20, 380, 201))
        self.videoWidget.setAutoFillBackground(False)
        self.videoWidget.setObjectName("videoWidget")
        self.heatmapLabel = QtWidgets.QLabel(main)
        self.heatmapLabel.setGeometry(QtCore.QRect(420, 20, 380, 201))
        self.heatmapLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.heatmapLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.heatmapLabel.setObjectName("heatmapLabel")
        self.statusLabel = QtWidgets.QLabel(main)
        self.statusLabel.setGeometry(QtCore.QRect(1140, 280, 71, 31))
        self.statusLabel.setScaledContents(False)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setIndent(-1)
        self.statusLabel.setObjectName("statusLabel")
        self.countingLabel = QtWidgets.QLabel(main)
        self.countingLabel.setGeometry(QtCore.QRect(830, 20, 380, 201))
        self.countingLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.countingLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.countingLabel.setObjectName("countingLabel")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(main)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 240, 1191, 39))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.buttonLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.buttonLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonLayout.setObjectName("buttonLayout")
        self.selectButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton.sizePolicy().hasHeightForWidth())
        self.selectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectButton.setFont(font)
        self.selectButton.setObjectName("selectButton")
        self.buttonLayout.addWidget(self.selectButton)
        self.heatmap = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heatmap.sizePolicy().hasHeightForWidth())
        self.heatmap.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.heatmap.setFont(font)
        self.heatmap.setObjectName("heatmap")
        self.buttonLayout.addWidget(self.heatmap)
        self.counting = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counting.sizePolicy().hasHeightForWidth())
        self.counting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.counting.setFont(font)
        self.counting.setObjectName("counting")
        self.buttonLayout.addWidget(self.counting)
        spacerItem = QtWidgets.QSpacerItem(600, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.submitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitButton.sizePolicy().hasHeightForWidth())
        self.submitButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.buttonLayout.addWidget(self.submitButton)
        self.statusTitle = QtWidgets.QLabel(main)
        self.statusTitle.setGeometry(QtCore.QRect(1090, 280, 61, 31))
        self.statusTitle.setScaledContents(False)
        self.statusTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.statusTitle.setIndent(-1)
        self.statusTitle.setObjectName("statusTitle")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "[FTP] Triple C"))
        self.heatmapLabel.setText(_translate("main", "Heatmap"))
        self.statusLabel.setText(_translate("main", "Not Ready"))
        self.countingLabel.setText(_translate("main", "Counting People"))
        self.selectButton.setText(_translate("main", "Select Video"))
        self.heatmap.setText(_translate("main", "Heatmap"))
        self.counting.setText(_translate("main", "Counting People"))
        self.submitButton.setText(_translate("main", "Submit"))
        self.statusTitle.setText(_translate("main", "Status:"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QDialog()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())
