# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Third.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(1024, 768)
        main.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        main.setAcceptDrops(False)
        main.setAutoFillBackground(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(main)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 1021, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.titleLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.titleLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.titleLayout.setContentsMargins(0, 0, 0, 0)
        self.titleLayout.setSpacing(0)
        self.titleLayout.setObjectName("titleLayout")
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.title.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.titleLayout.addWidget(self.title)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(main)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(50, 130, 371, 271))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.menuLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.menuLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.menuLayout.setContentsMargins(0, 0, 0, 0)
        self.menuLayout.setSpacing(0)
        self.menuLayout.setObjectName("menuLayout")
        self.selectButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectButton.sizePolicy().hasHeightForWidth())
        self.selectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.selectButton.setFont(font)
        self.selectButton.setObjectName("selectButton")
        self.menuLayout.addWidget(self.selectButton)
        self.heatmap = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heatmap.sizePolicy().hasHeightForWidth())
        self.heatmap.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.heatmap.setFont(font)
        self.heatmap.setObjectName("heatmap")
        self.menuLayout.addWidget(self.heatmap)
        self.movementline = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movementline.sizePolicy().hasHeightForWidth())
        self.movementline.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.movementline.setFont(font)
        self.movementline.setObjectName("movementline")
        self.menuLayout.addWidget(self.movementline)
        self.movementheatmap = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.movementheatmap.sizePolicy().hasHeightForWidth())
        self.movementheatmap.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.movementheatmap.setFont(font)
        self.movementheatmap.setObjectName("movementheatmap")
        self.menuLayout.addWidget(self.movementheatmap)
        self.counting = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.counting.sizePolicy().hasHeightForWidth())
        self.counting.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.counting.setFont(font)
        self.counting.setObjectName("counting")
        self.menuLayout.addWidget(self.counting)
        self.submitButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitButton.sizePolicy().hasHeightForWidth())
        self.submitButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.menuLayout.addWidget(self.submitButton)
        self.showWidget = QVideoWidget(main)
        self.showWidget.setGeometry(QtCore.QRect(500, 130, 480, 270))
        self.showWidget.setAutoFillBackground(False)
        self.showWidget.setObjectName("showWidget")
        self.widget_2 = QVideoWidget(main)
        self.widget_2.setGeometry(QtCore.QRect(500, 450, 480, 270))
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(main)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(670, 400, 171, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.peopleBox = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.peopleBox.setContentsMargins(0, 0, 0, 0)
        self.peopleBox.setObjectName("peopleBox")
        self.peopleNo = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.peopleNo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.peopleNo.setSmallDecimalPoint(False)
        self.peopleNo.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.peopleNo.setObjectName("peopleNo")
        self.peopleBox.addWidget(self.peopleNo)
        self.peopleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.peopleLabel.setFont(font)
        self.peopleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.peopleLabel.setObjectName("peopleLabel")
        self.peopleBox.addWidget(self.peopleLabel)

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Dialog"))
        self.title.setText(_translate("main", "[FTP] CCC System Beta"))
        self.selectButton.setText(_translate("main", "Select Video"))
        self.heatmap.setText(_translate("main", "Heatmap"))
        self.movementline.setText(_translate("main", "Movement line"))
        self.movementheatmap.setText(_translate("main", "Movement heatmap"))
        self.counting.setText(_translate("main", "Counting people"))
        self.submitButton.setText(_translate("main", "Submit"))
        self.peopleLabel.setText(_translate("main", "People"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QDialog()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())
